# https://www.playframework.com/documentation/latest/Configuration
play.application.loader = "com.mendev.apistore.AppLoader"
app {
  database {
    host = ${MYSQL_HOST}
    port = ${MYSQL_PORT}
    name = ${MYSQL_DATABASE}
    user = ${MYSQL_USER}
    password = ${MYSQL_PASSWORD}
    pool-size = 10
    pool-size = ${?DB_POOL_SIZE}
  }
  mail {
    host = ${MAIL_HOST}
    port = ${MAIL_PORT}
    user = ${MAIL_USER}
    password = ${MAIL_PASSWORD}
    from = ${MAIL_FROM}
  }
  jwt {
    secret = ${JWT_SECRET}
    access-token-ttl = 15 minutes
    access-token-ttl = ${?JWT_ACCESS_TOKEN_TTL}
    refresh-token-ttl = 30 days
    refresh-token-ttl = ${?JWT_REFRESH_TOKEN_TTL}
  }
}

play.mailer {
  host = ${app.mail.host}
  port = ${app.mail.port}
  user = ${app.mail.user}
  password = ${app.mail.password}
}

db.default {
  driver = "com.mysql.cj.jdbc.Driver"
  url = "jdbc:mysql://"${app.database.host}":"${app.database.port}"/"${app.database.name}
  username = ${app.database.user}
  password = ${app.database.password}
  hikaricp.maximumPoolSize = ${app.database.pool-size}
}

db-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = ${app.database.pool-size}
  }
  throughput = 1
}