# https://www.playframework.com/documentation/latest/Configuration
play.modules.enabled += "shared.config.ConfigModule"
play.modules.enabled += "shared.db.FlywayModule"
play.http.errorHandler = "shared.web.JsonErrorHandler"
app {
  database {
    host = ${MYSQL_HOST}
    port = ${MYSQL_PORT}
    name = ${MYSQL_DATABASE}
    user = ${MYSQL_USER}
    password = ${MYSQL_PASSWORD}
  }
  mail {
    host = ${MAIL_HOST}
    port = ${MAIL_PORT}
    user = ${MAIL_USER}
    password = ${MAIL_PASSWORD}
    from = ${MAIL_FROM}
  }
}